### ISSUE TITLE
Update react-beautiful-dnd in favor of React 18

### ISSUE THREAD

**Issue by amitsingh-007** [amitsingh-007/bypass-links#1517]
* New repo: [Forked](https://github.com/react-forked/dnd)
* Re-enable `StrictMode`
* Remove `--legacy-peer-deps` from `.npmrc`

**Comment by amitsingh-007** [comment]
Check this also: https://github.com/react-forked/dnd/issues/293

**Comment by amitsingh-007** [comment]
New working fork created: https://github.com/atlassian/react-beautiful-dnd/issues/2399#issuecomment-1213532725

**Comment by Xhale1** [comment]
Hey! I'm the maintainer of the new fork Pangea Dnd. You should be able to drop in my library by replacing `react-beautiful-dnd` with `@hello-pangea/dnd`.

Let me know if you run into any issues 👍

**Comment by amitsingh-007** [comment]
Yeah, I will try this fork and create issues on your repo if found.
