### ISSUE TITLE
Does not bypass 

### ISSUE THREAD

**Issue by githubprogit** [amitsingh-007/bypass-links#1882]
Does not bypass the link like olamovies

**Comment by amit-debugger** [comment]
Hey, thanks for opening this issue but unfortunately this project is meant for an organisation that I freelance.I just open sourced some part of it so that other people can fork it and use it.

**Comment by amit-debugger** [comment]
Sorry but I can't support extra features as this gets built as an internal component for some other stuff. You can always fork and support your needs and self host it

**Comment by amitsingh-007** [comment]
Hey, thanks for opening this issue but unfortunately this project is meant for an organisation that I freelance.I just open sourced some part of it so that other people can fork it and use it.

**Comment by amitsingh-007** [comment]
Sorry but I can't support extra features as this gets built as an internal component for some other stuff. You can always fork and support your needs and self host it
