### ISSUE TITLE
Explore other React component libs

### ISSUE THREAD

**Issue by amit-debugger** [amitsingh-007/bypass-links#2141]
#### MantineUI
* Pros
  * Closest to mui(have global props/styles like mui, dark mode)
  * A lot of components
  * Uses emotion like mui
  * A lot of inbuilt hooks like debounce and all
  * Supports ssr in nextjs like mui
* Cons
  * doesn't have same responsive API like mui
  * Not sure about future of lib
  * Maybe(no idea) if promotion on reddit is real or not

#### NextUI (not associated with nextjs/vercel)
* Pros
   * Nice looking like vercel
* Cons
  * In beta, so not a lot of components
  * Not sure about perf

#### MUI6
* Dev not started yet

### Joy UI from MUI
* Very less components ig

**Comment by amit-debugger** [comment]
mantine's font and ui looks good and modern. check package size and all components that we use

**Comment by amitsingh-007** [comment]
https://github.com/amitsingh-007/bypass-links/issues/2144
